apiVersion: apps/v1
kind: Deployment
metadata:
    name: react-todo-k8s
    labels:
        app: react-todo-k8s
spec:
    replicas: 2
    selector:
        matchLabels:
            app: react-todo-k8s
    template:
        metadata:
        labels:
            app: react-todo-k8s
    spec:
        containers:
        -   name: react-todo-k8s
            image: chanutpong/react-todo-k8s
            ports:
            -   containerPort: 3000
            resources:
                limits:
                    memory: '128Mi'
                    cpu: '200m'
            livenessProbe:
                httpGet:
                    path: /index.html
                    port: 3000
                initialDelaySeconds: 15
                timeoutSeconds: 2
                periodSeconds: 5
                failureThreshold: 1
             readinessProbe:
                httpGet:
                    path: /index.html
                    port: 3000
                initialDelaySeconds: 15
                periodSeconds: 5
                failureThreshold: 1