apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: react-todo-k8s
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: react-todo-k8s
  minReplicas: 1
  maxReplicas: 10
  metrics:
  - type: Resource
    resource:
      name: cpu
      targetAverageUtilization: 50