apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: test-ingress
  namespace: default
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/rewrite-target: /$2
    nginx.ingress.kubernetes.io/proxy-read-timeout: "12h"
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
    
spec:
  rules:
  - host: myk8s
    http:
      paths:
      - path: /(/|$)(.*)
        backend:
          serviceName: nginx
          servicePort: 80
      - path: /react/(/|$)(.*)
        backend:
          serviceName: react-todo-k8s-service
          servicePort: 80
  # rules:
  # - http:
  #     paths:
  #     - backend:
  #         serviceName: react-todo-k8s-service
  #         servicePort: 80
  # rules:
  # - http:
  #     paths:
  #     - path: /react
  #       backend:
  #         serviceName: react-todo-k8s-service
  #         servicePort: 80